### ISSUE TITLE
Missing `firebase_options.dart`

### ISSUE THREAD

**Issue by domesticmouse** [Mayank-9018/AchieversJournal#1]
The `import 'firebase_options.dart';` in `lib/main.dart` isn't referring to a checked in file.

**Comment by Mayank-9018** [comment]
`firebase_options.dart` is automatically generated by FlutterFire CLI, and contains apiKey, apiId and probably other sensitive data. Is it right to track it in git?

**Comment by domesticmouse** [comment]
I've checked in a version of the file with the various IDs removed. You can see an example of this approach in https://github.com/flutter/codelabs/blob/master/firebase-get-to-know-flutter/step_09/lib/firebase_options.dart

hth!
